baseURL = "https://summeerorg.github.io/"
locale = "en-US"
title = "SUMMEER"
theme = "gokarna-hugo"
enableEmoji = true

[params]
  description = "SUstainable Material Management Extreme Events Reconnaissance (SUMMEER) Organization"
  avatarURL = "/images/SUMMEER.png"
  avatarAltText = "SUMMEER"
  avatarSize = "size-m"
  showBackToTopButton = true
  customHeadHTML = '''
<link rel="icon" type="image/png" href="/images/SUMMEER.png">

<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">



<script async src="https://www.googletagmanager.com/gtag/js?id=G-1WZSE8DHZ9"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'G-1WZSE8DHZ9');
</script>

'''

  socialIcons = [
    {name = "github", url = "https://github.com/"},
    {name = "twitter", url = "https://x.com/"},
    {name = "linkedin", url = "https://www.linkedin.com/"},
    {name = "google", url = "https://scholar.google.com/"},
    {name = "researchgate", url = "https://www.researchgate.net/"},
    {name = "goodreads", url = "https://www.goodreads.com/"},
    {name = "youtube", url = "https://www.youtube.com/"},
    {name = "email", url = "mailto:"}
  ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Webinars"
    url = "/Webinars/"
    weight = 2

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

 
